# Generated by Django 2.1.7 on 2022-03-25 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220325_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 25, 14, 46, 45, 684472)),
        ),
    ]
